[build]
  command = """
    mkdir -p dist \
    && cp index.html dist/index.html \
    && cp style.css dist/style.css \
    && npm --prefix vintageSalon install \
    && npm --prefix vintageSalon run build \
    && mkdir -p dist/newdd \
    && mkdir -p dist/sanistar-userguide \
    && mkdir -p dist/sla-tool \
    && cp -R newDD/* dist/newdd/ \
    && cp -R sla=tool/* dist/sla-tool/ \
    && cp -R sanistar-userguide/* dist/sanistar-userguide/
  """
  publish = "dist"